### ISSUE TITLE
0D.09.关于内网穿透，第三方集成调试

### ISSUE THREAD

**Issue by alanfans** [fessionalpro/wings-doc#1]
加入    * 钉钉提供的内网穿透工具 ngrok - <https://github.com/open-dingtalk/dingtalk-pierced-client>
此工具免费可用。

**Comment by trydofor** [comment]
多谢，已添加

**Comment by trydofor** [comment]
看起来，已经停用了。
https://github.com/open-dingtalk/dingtalk-pierced-client/issues/13

https://open.dingtalk.com/document/resourcedownload/http-intranet-penetration
